name: assistant_beta_openai
description: This package is designed to integrate OpenAI's assistant beta api into Flutter applications
version: 0.1.1
homepage: https://github.com/yunusemrealpak/openai_assistant

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  busenet: ^0.8.6
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
